In [1]:
import re
import matplotlib.pyplot as plt
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree
import pydotplus


In [30]:
def load_one_flle(filename):
    x=[]
    with open(filename) as f:
        line=f.readline()
        line=line.strip('\n')
    return line

def load_adfa_training_files(rootdir):
    x=[]
    y=[]
    list = os.listdir(rootdir)
    # print(list)
    for i in range(0, len(list)):
        path = os.path.join(rootdir, list[i])
        if os.path.isfile(path):
            # print(path)
            x.append(load_one_flle(path))
            y.append(0)
    return x,y

def dirlist(path, allfile):
    filelist = os.listdir(path)

    for filename in filelist:
        filepath = os.path.join(path, filename)
        if os.path.isdir(filepath):
            dirlist(filepath, allfile)
        else:
            allfile.append(filepath)
    return allfile

def load_adfa_hydra_ftp_files(rootdir):
    x=[]
    y=[]
    allfile=dirlist(rootdir,[])
    # print(allfile)
    for file in allfile:
        if re.match(r"../../Data/ADFA-LD/Attack_Data_Master/Hydra_FTP_\d+\\UAD-Hydra-FTP*",file):
            # print(file)
            x.append(load_one_flle(file))
            y.append(1)
    return x,y

In [44]:
x1,y1=load_adfa_training_files("../../Data/ADFA-LD/Training_Data_Master/")

x2,y2=load_adfa_hydra_ftp_files("../../Data/ADFA-LD/Attack_Data_Master/")
x=x1+x2#拼接
y=y1+y2

vectorizer = CountVectorizer(min_df=1)

x=vectorizer.fit_transform(x)
# print(vectorizer.get_feature_names())
print(len(vectorizer.get_feature_names()))
print(x)
x=x.toarray()
print(x)
print(len(x))
clf = tree.DecisionTreeClassifier()
a=cross_val_score(clf, x, y, n_jobs=-1, cv=10)
print(a)
print(np.mean(a))
clf = clf.fit(x, y)
dot_data = tree.export_graphviz(clf, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("./ftp.pdf")

142
  (0, 127)	1
  (0, 121)	1
  (0, 10)	2
  (0, 46)	1
  (0, 5)	2
  (0, 81)	267
  (1, 10)	24
  (1, 124)	10
  (1, 35)	61
  (1, 8)	3
  (1, 34)	5
  (1, 17)	3
  (2, 46)	1
  (2, 124)	1
  (2, 35)	1
  (2, 34)	2
  (2, 3)	1
  (2, 123)	3
  (2, 112)	9
  (2, 44)	23
  (2, 48)	10
  (2, 80)	1
  (2, 12)	9
  (2, 136)	3
  (2, 85)	1
  :	:
  (990, 90)	68
  (991, 46)	28
  (991, 47)	16
  (991, 0)	13
  (991, 135)	42
  (991, 1)	116
  (991, 90)	10
  (991, 94)	28
  (991, 107)	51
  (992, 46)	29
  (992, 47)	16
  (992, 0)	19
  (992, 135)	41
  (992, 1)	114
  (992, 90)	15
  (992, 94)	28
  (992, 107)	42
  (993, 10)	24
  (993, 8)	1
  (993, 1)	29
  (993, 94)	3
  (994, 44)	3
  (994, 48)	4
  (994, 136)	19
  (994, 30)	3
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 19 114   0 ...   0   0   0]
 [  0  29   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
995
[1.         0.98       0.96       0.98       0.96       0.87878788
 0.98989899 0.97979798 0.96969697 0.94949495]

True