# 7.3　Hello World！OpenAI Gym

In [1]:
! pip show gym

Name: gym
Version: 0.26.2
Summary: Gym: A universal API for reinforcement learning environments
Home-page: https://www.gymlibrary.dev/
Author: Gym Community
Author-email: jkterry@umd.edu
License: MIT
Location: d:\anaconda\envs\keras_rl2\lib\site-packages
Requires: cloudpickle, gym-notices, importlib-metadata, numpy
Required-by: 


In [2]:
import gym
import time
env = gym.make('CartPole-v1')
observation = env.reset()
observation

(array([ 0.00901061, -0.02583191, -0.015197  ,  0.0295292 ], dtype=float32),
 {})

In [3]:
print("env actionspace：")
env.action_space

env actionspace：


Discrete(2)

In [4]:
print("env observationspace：")
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)

env observationspace：
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [5]:
count = 0
for t in range(100):
    #随机选择一个动作
    action = env.action_space.sample()
    #执行动作 获取环境反馈
    observation, reward, terminated, truncated, info = env.step(action)
    # terminated 和 truncated 都是布尔值，分别表示环境是否因任务完成而终止，以及是否因达到最大步数而截断。
    done = terminated or truncated
    #如果玩死了就退出
    if done:
        break
    env.render()
    count+=1
    time.sleep(0.2)
print(count)

d:\Anaconda\envs\keras_rl2\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
d:\Anaconda\envs\keras_rl2\lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(


20


# 7.4　编写OpenAI Gym环境

In [6]:
import numpy
import random
from gym import spaces
import gym


class GridEnv(gym.Env):
    metadata = {
        'render.modes': ['human', 'rgb_array'],
        'video.frames_per_second': 2
    }

    def __init__(self):

        self.states = [1,2,3,4,5,6,7,8]

        self.terminate_states = dict()
        self.terminate_states[6] = 1
        self.terminate_states[7] = 1
        self.terminate_states[8] = 1

        self.actions = ['n','e','s','w']

        self.rewards = dict();
        self.rewards['1_s'] = -1.0
        self.rewards['3_s'] = 1.0
        self.rewards['5_s'] = -1.0

        self.t = dict();
        self.t['1_s'] = 6
        self.t['1_e'] = 2
        self.t['2_w'] = 1
        self.t['2_e'] = 3
        self.t['3_s'] = 7
        self.t['3_w'] = 2
        self.t['3_e'] = 4
        self.t['4_w'] = 3
        self.t['4_e'] = 5
        self.t['5_s'] = 8
        self.t['5_w'] = 4

        self.gamma = 0.8
        self.viewer = None
        self.state = None

    def getTerminal(self):
        return self.terminate_states

    def getGamma(self):
        return self.gamma

    def getStates(self):
        return self.states

    def getAction(self):
        return self.actions
    def getTerminate_states(self):
        return self.terminate_states
    def setAction(self,s):
        self.state=s

    def _step(self, action):

        state = self.state
        #判断是否游戏结束
        if state in self.terminate_states:
            return state, 0, True, {}
        key = "%d_%s"%(state, action)
        #查找状态迁移表
        if key in self.t:
            next_state = self.t[key]
        else:
            #查不到就状态不变
            next_state = state
        self.state = next_state

        is_terminal = False

        if next_state in self.terminate_states:
            is_terminal = True

        if key not in self.rewards:
            r = 0.0
        else:
            r = self.rewards[key]


        return next_state, r,is_terminal,{}
    def _reset(self):
        self.state = self.states[int(random.random() * len(self.states))]
        return self.state
    def render(self, mode='human', close=False):
        return

要适配0.26.2的gym版本，需要修改gold.py文件，具体的代码放在了:
```bash
gym
|--envs
|    |--classic_control
|           |--__init__.py
|           |--gold.py
|--__init__.py
```

In [7]:

import gym
env = gym.make('Gold-v0')